### PR TITLE
some changes on Treats website

### PR DESCRIPTION
**Pull request by MindyZHAOMinzhu**

### CODE REVIEW

**Review by ivywze — COMMENTED** [review]
seems fine, just could modify the layout to make it looks neater.

**Comment by MindyZHAOMinzhu** [comment]
Some new changes

**Comment by hupili** [comment]
@MindyZHAOMinzhu did you send PR to the wrong repo? i.e. I see some updates here: https://github.com/hupili/big-road/pull/1

**Comment by hupili** [comment]
@MindyZHAOMinzhu  besides those technical improvements asked by @ivyWANG958 , you may also want to make your commit message more formal and informative. See here for some reference: https://github.com/hupili/python-for-data-and-media-communication-gitbook/blob/master/guide-for-contributor.md#git-commit-message

Commit message is an important medium for our communication, especially in the open source world where people work together all over the world, across timezones, in asynchronous manner.

**Comment by MindyZHAOMinzhu** [comment]
> @MindyZHAOMinzhu did you send PR to the wrong repo? i.e. I see some updates here: [hupili/big-road#1](https://github.com/hupili/big-road/pull/1)

Yes, I pull a a wrong request at first😢.

**Comment by MindyZHAOMinzhu** [comment]
> @MindyZHAOMinzhu besides those technical improvements asked by @ivyWANG958 , you may also want to make your commit message more formal and informative. See here for some reference: https://github.com/hupili/python-for-data-and-media-communication-gitbook/blob/master/guide-for-contributor.md#git-commit-message
> 
> Commit message is an important medium for our communication, especially in the open source world where people work together all over the world, across timezones, in asynchronous manner.

Sorry for that!! OK!!! I will check it!! Thank you!!! ❤️

**Comment by hupili** [comment]
@MindyZHAOMinzhu , actually, you don't have send new PR to address the above comments or Ivy's feedback. You just keep modifying `MindyZHAOMinzhu:gh-pages` branch and the updates will show here automatically. Please try. GH workflow is very convenient once you get used to it.

**Comment by MindyZHAOMinzhu** [comment]
> @MindyZHAOMinzhu , actually, you don't have send new PR to address the above comments or Ivy's feedback. You just keep modifying `MindyZHAOMinzhu:gh-pages` branch and the updates will show here automatically. Please try. GH workflow is very convenient once you get used to it.

Should I pull a new request? I have tried to to pull a new request. I am a little confused with GH work flow.

**Comment by hupili** [comment]
you don't have send new PR. Please work in `MindyZHAOMinzhu` repo and modify `gh-pages` branch.

Then we will see the changes directly.

Please consult @ivyWANG958  on the details. First time is always confusing.

**Comment by MindyZHAOMinzhu** [comment]
> you don't have send new PR. Please work in `MindyZHAOMinzhu` repo and modify `gh-pages` branch.
> 
> Then we will see the changes directly.
> 
> Please consult @ivyWANG958 on the details. First time is always confusing.

Ok !!!! I will ask Ivy for help if I I have any question. Thank you !!!

**Comment by hupili** [comment]
@ivyWANG958  please help @MindyZHAOMinzhu with this PR after final.

**Comment by hupili** [comment]
@ivyWANG958 , can you help to check if the content is correct via following steps?

```
git checkout -b MindyZHAOMinzhu-gh-pages gh-pages
git pull https://github.com/MindyZHAOMinzhu/datavis.studio.git gh-pages
```

Then, you will have a local copy of Mindy's latest pages. You can preview to see if things are alright. That local preview will be online once we click "Merge Pull Request" on this page.

**Comment by ivywze** [comment]
Okay, thanks for the instructions. I’ll follow up after the finals.

**Comment by ivywze** [comment]
@MindyZHAOMinzhu if you are going to keep modifying, here are some possible updates to make the page more attractive:
- explain the message you want to pass to others. e.g. the "關注點四：缺乏接觸和認識的機會" section could add more explanatory paragraphs. 
- change the content that presents in the images in your own way. e.g. draw the circle of “惡性循環” and make the chart and mark annotation in "校園共融和排斥現況調查“, add the code into the page instead of the image.
- make one section consistent. e.g. the "【孤獨海洋】自閉症少年不諳水性　揚帆破浪助自立　代表港出賽" reading could be aligned with the other two, and make them 1:1:1 in one row when display on PC. You may also change all the title to Chinese.
- notice the details. e.g. there is one encoding problem in "多達7成半(74.3%)家長認為社會人士不懂得與自閉症人士合作及���通".

**Comment by MindyZHAOMinzhu** [comment]
> @MindyZHAOMinzhu if you are going to keep modifying, here are some possible updates to make the page more attractive:
> 
> * explain the message you want to pass to others. e.g. the "關注點四：缺乏接觸和認識的機會" section could add more explanatory paragraphs.
> * change the content that presents in the images in your own way. e.g. draw the circle of “惡性循環” and make the chart and mark annotation in "校園共融和排斥現況調查“, add the code into the page instead of the image.
> * make one section consistent. e.g. the "【孤獨海洋】自閉症少年不諳水性　揚帆破浪助自立　代表港出賽" reading could be aligned with the other two, and make them 1:1:1 in one row when display on PC. You may also change all the title to Chinese.
> * notice the details. e.g. there is one encoding problem in "多達7成半(74.3%)家長認為社會人士不懂得與自閉症人士合作及���通".

Ok! Thank you! I will modify the website later to polish it!

**Comment by MindyZHAOMinzhu** [comment]
> @MindyZHAOMinzhu if you are going to keep modifying, here are some possible updates to make the page more attractive:
> 
> * explain the message you want to pass to others. e.g. the "關注點四：缺乏接觸和認識的機會" section could add more explanatory paragraphs.
> * change the content that presents in the images in your own way. e.g. draw the circle of “惡性循環” and make the chart and mark annotation in "校園共融和排斥現況調查“, add the code into the page instead of the image.
> * make one section consistent. e.g. the "【孤獨海洋】自閉症少年不諳水性　揚帆破浪助自立　代表港出賽" reading could be aligned with the other two, and make them 1:1:1 in one row when display on PC. You may also change all the title to Chinese.
> * notice the details. e.g. there is one encoding problem in "多達7成半(74.3%)家長認為社會人士不懂得與自閉症人士合作及���通".

Ivy, I have make some changes on the website, it looks better now. 
Thank you!!!! 
However, I did not find proper circular arrow flow chart to replace the the original picture. So I just main the original one and did not change this part.

**Pull request merged**
