### PR TITLE
rebuilt course web using only html

### PR DESCRIPTION
**Pull request by ivywze**

### CODE REVIEW

**Comment by hupili** [comment]
@ivyWANG958 , for the embed URL of the slides, you can observe the URL pattern and spell out the new ones.

For example, you can find one example URL from previous website:

https://docs.google.com/presentation/d/1y-yZbCO4MznzUH66HgV_U3smiU9d9VAo4AauwS7PYio/embed?start=false&loop=false&delayms=3000&slide=id.p

Following is week3 slides for spring 2019 term. 

https://docs.google.com/presentation/d/1XMQwm79Ac9-SClOIiKDsKZaHNZ0qtO8khyg9Ct0Qf54/edit#slide=id.p

You will find the key difference is the `/edit` or `/embed` part with their corresponding URL parameters. Before that part is the unique ID to the Google file

We can spell out the embed URL as follows:

https://docs.google.com/presentation/d/1XMQwm79Ac9-SClOIiKDsKZaHNZ0qtO8khyg9Ct0Qf54/embed?start=false&loop=false&delayms=3000&slide=id.p

Note that you can also add other parameters for how this is embedded, e.g. start from which slides. You should understand their function by the name.

**Comment by hupili** [comment]
@ivyWANG958 , please also handle following two updates:

* [ ] Use this new bio in my introduction: http://www.jour.hkbu.edu.hk/faculty-member/mr-pili-hu/
* [ ] Merge the suggested reading/ learning resources from 2017 version into this page.

p.s. You can push to your `gh-pages` directly without creating new PR. The changes will reflect here.

**Comment by ivywze** [comment]
> @ivyWANG958 , please also handle following two updates:
> 
> * [ ]  Merge the suggested reading/ learning resources from 2017 version into this page.

Here do you mean the slides from the previous class?

**Comment by hupili** [comment]
> Here do you mean the slides from the previous class?

No. Not the previous slides. I remember there was a section giving some data viz resources, e.g. tools catalogue, dataset, etc. We can put those on the resources section. This is a continuous effort. We can build an initial list first and keep growing. Following two can be added to the list.


> One common obstacle for beginner is to choose right chart for the right dataset. For general data-viz inspirations, you can refer to the following two sites:
>
> - https://datavizproject.com/
> - https://datavizcatalogue.com/

**Pull request merged**
