### PR TITLE
TREATS landing page stage1

### PR DESCRIPTION
**Pull request by ivywze**

### CODE REVIEW

**Comment by hupili** [comment]
Some content wise updates:

* [ ] 關注點2：缺乏社交機會。添加一些圖表。  P22/ P23 
* [ ] 倡議，4個圖標，P42  （後面的細節可以不用了）
* [ ] 最後的版權部分。 “Untitled” —> “TREATS, 2019”  ; “Web Design: Ivy Wang; Template: HTML5 UP; Course Partner: HKBU/JOUR2106”. HKBU/JOUR2106 加鏈接 http://datavis.studio/

**Comment by hupili** [comment]
For the cover photo. `background-size: cover` can help to preserve the aspect ratio.

Current status:

screenshot 2019-02-21 at 11 30 46 am

`cover`:

screenshot 2019-02-21 at 11 31 40 am

screenshot 2019-02-21 at 11 33 02 am

**Comment by ivywze** [comment]
Almost there, just left this one:

> 關注點2：缺乏社交機會。添加一些圖表。  P22/ P23

will keep modifying tomorrow.

**Comment by hupili** [comment]
@ivyWANG958  I just merged current progress to test if things work alright on the production location (common issue is relative/ absolute path).  It seems alright: http://datavis.studio/2019/TREATS/?zgb342g

Please create new PR and keep updating.

Cheers

**Pull request merged**
